### PR TITLE
Remove buildroot references from {tcl,tk}Config.sh scripts

### PR DESCRIPTION
**Pull request by nehaljwani**
Resolves https://github.com/conda-forge/tk-feedstock/issues/45
xref: https://src.fedoraproject.org/rpms/tk/blob/f32/f/tk.spec#_82

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin Please re-render!

**Comment by ocefpaf** [comment]
LGTM but I'm no expert on this. @jjhelmus do you mind taking a quick look?

**Comment by jjhelmus** [comment]
LGTM

**Comment by jjhelmus** [comment]
Thanks @nehaljwani

**Pull request merged**
