### PR TITLE
Install TCL private headers

### PR DESCRIPTION
**Pull request by andersharrisson-ess**
To be able to build Tcl extensions, the private header files should be packaged as well.

### CODE REVIEW

**Comment by andersharrisson-ess** [comment]
@conda-forge-admin, please rerender

**Comment by andersharrisson-ess** [comment]
My change only affects the Linux/MacOS builds. I tried to find out how to implement it for the Windows builds, but without access to a Windows machine I simply could not test any implementation.

**Comment by jjhelmus** [comment]
LGTM, thanks for the update @andersharrisson-ess.  Sorry this took so long to review.

**Comment by andersharrisson-ess** [comment]
Thank you for the review and merge, @jjhelmus. Much appreciated.

**Pull request merged**
